"""
Django settings for student_system project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ─── Minimal .env loader (no third-party packages needed) ────────────────────
def _load_env(env_path):
    """Read KEY=VALUE lines from a .env file into os.environ."""
    try:
        with open(env_path, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                key, _, value = line.partition('=')
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                os.environ.setdefault(key, value)
    except FileNotFoundError:
        pass  # .env is optional


_load_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-w!33qjwms^$*2t!^!le!929r@*vkfr$9@5%v7f4m&$s$(!c*o*'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS — include Vercel domains; filter out empty strings
_vercel_url = os.environ.get('VERCEL_URL', '')   # e.g. myapp-abc123.vercel.app
ALLOWED_HOSTS = list(filter(None, [
    'localhost',
    '127.0.0.1',
    '.vercel.app',    # covers all *.vercel.app subdomains
    '.now.sh',        # legacy Vercel domains
    _vercel_url,      # specific deployment URL (empty string filtered out)
]))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'student_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files on Vercel
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'student_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'student_system.wsgi.application'


# Database — Supabase PostgreSQL
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# DATABASE_URL format: postgresql://user:password@host:port/dbname

def _parse_db_url(url):
    """Parse a DATABASE_URL into a Django DATABASES dict.

    Handles passwords containing special characters (e.g. '@') by
    splitting on the LAST '@' sign before the host.
    """
    from urllib.parse import unquote
    # Strip scheme
    rest = url.split('://', 1)[1]          # postgres:PASSWORD@HOST:PORT/NAME
    # Split userinfo from host — last '@' separates them
    at_idx = rest.rfind('@')
    userinfo = rest[:at_idx]               # postgres:PASSWORD
    hostinfo = rest[at_idx + 1:]           # HOST:PORT/NAME

    # Parse user:password
    if ':' in userinfo:
        user, password = userinfo.split(':', 1)
    else:
        user, password = userinfo, ''

    # Parse host:port/dbname
    if '/' in hostinfo:
        hostport, dbname = hostinfo.split('/', 1)
    else:
        hostport, dbname = hostinfo, ''

    if ':' in hostport:
        host, port = hostport.rsplit(':', 1)
    else:
        host, port = hostport, '5432'

    return {
        'ENGINE':   'django.db.backends.postgresql',
        'NAME':     unquote(dbname),
        'USER':     unquote(user),
        'PASSWORD': unquote(password),   # handles %40 etc.
        'HOST':     host,
        'PORT':     port,
        'OPTIONS':  {'sslmode': 'require'},
    }


_db_url = os.environ.get('DATABASE_URL', '')

if _db_url and 'YOUR_DB_PASSWORD' not in _db_url and (_db_url.startswith('postgresql') or _db_url.startswith('postgres')):
    # Use Supabase PostgreSQL
    DATABASES = {'default': _parse_db_url(_db_url)}
else:
    # Fallback: local SQLite (until password is filled in .env)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Supabase client credentials
SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
SUPABASE_PUBLISHABLE_KEY = os.environ.get('SUPABASE_PUBLISHABLE_KEY', '')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Vercel / production: WhiteNoise serves compressed files directly from STATICFILES_DIRS
# Using CompressedStaticFilesStorage (NOT Manifest) so collectstatic is not required on Vercel
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
WHITENOISE_USE_FINDERS = True  # Serve from STATICFILES_DIRS without collectstatic

# Media files (local dev only; use cloud storage in production)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─── Production Security (active when DEBUG=False on Vercel) ─────────────────
if not DEBUG:
    # Tell Django to trust Vercel's edge SSL termination
    # Vercel sends HTTP internally; X-Forwarded-Proto: https is the real signal
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # DO NOT set SECURE_SSL_REDIRECT on Vercel — the edge already handles HTTPS.
    # Setting it causes Django to loop-redirect HTTP → HTTPS endlessly → 500.
    # SECURE_SSL_REDIRECT = True   ← intentionally disabled for Vercel

    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
